### PR TITLE
*[change]  lua-resty-redis-cluster

### PR DESCRIPTION
**Pull request by yjpshr**
This pr provides the lua client for the redis cluster.

### CODE REVIEW

**Comment by zhengfengshaw** [comment]
why not merged? @yjpshr

**Comment by vladimir-kazan** [comment]
Please, merge it

**Comment by sysword** [comment]
Please, merge it

**Comment by debjit-chat** [comment]
Is there any issue for not merging this still now?

**Comment by zhuizhuhaomeng** [comment]
cluster support should be in another  repo.

**Pull request closed without merging**
