### PR TITLE
Add support for HyperLogLog pfadd, pfcount and pfmerge commands.

### PR DESCRIPTION
**Pull request by arohter**

### CODE REVIEW

**Comment by agentzh** [comment]
@arohter Just a quick heads up: I will look into this soon. I'm currently too busy with other things. Sorry for the delay on my side!

**Comment by arohter** [comment]
No problem.  We've been running our patch branch a few weeks now on for https://github.com/fanhattan/lua-resty-api-metrics ; working great.

**Comment by agentzh** [comment]
@arohter Glad to hear that. This is still on my review queue though. Sorry about that.

**Comment by toredash** [comment]
@agentzh any chance of getting this into the repository ?

**Review by zhuizhuhaomeng — APPROVED** [review]

**Pull request closed without merging**
